language: generic

sudo: required
services: 
  - docker

before_install:
  - docker build -t javascratches/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true javascratches/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "wklej
  bucket_name: "wklej"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
