language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t javascratches/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true javascratches/docker-react npm run test -- --watchAll=false
